# Based partially on Alyxia's work, thanks so much!

name: Release
on:
  push:
    tags:
      - v*
  schedule:
    - cron: "30 0 */14 * *"
  workflow_dispatch: 

env:
  FORCE_COLOR: true
  RELEASE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || format('build-{0}', github.run_number) }}

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y pkg-config libsdl2-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libglx-dev libgl1-mesa-dev libxxf86vm-dev libglfw3-dev libwayland-dev libwayland-egl1 libegl-dev libxkbcommon-dev wayland-protocols extra-cmake-modules

      - name: Install Go dependencies
        run: go get -v

      - name: Recreate vendor and apply Wayland patches
        run: |
          go mod vendor
          git apply patches/wayland.patch

      - name: Build GUI (X11)
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -tags static -ldflags "-s \
          -w -X 'equilotl/buildinfo.InstallerGitHash=$(git rev-parse --short \
          HEAD)' -X 'equilotl/buildinfo.InstallerTag=${{ env.RELEASE_TAG }}'" -o \
          Equilotl-x11

      - name: Build GUI (Wayland)
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -tags "static wayland" \
          -ldflags "-s -w -X 'equilotl/buildinfo.InstallerGitHash=$(git \
          rev-parse --short HEAD)' -X 'equilotl/buildinfo.InstallerTag=${{ env.RELEASE_TAG }}'" -o Equilotl-wayland

      - name: Build GUI (Combined)
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -tags "static combined" \
          -ldflags "-s -w -X 'equilotl/buildinfo.InstallerGitHash=$(git \
          rev-parse --short HEAD)' -X 'equilotl/buildinfo.InstallerTag=${{ env.RELEASE_TAG }}'" -o Equilotl

      - name: Build CLI
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -tags "cli" -ldflags "-s \
          -w -X 'equilotl/buildinfo.InstallerGitHash=$(git rev-parse --short \
          HEAD)' -X 'equilotl/buildinfo.InstallerTag=${{ env.RELEASE_TAG }}'" -o \
          EquilotlCli-linux

      - name: Update executable
        run: |
          chmod +x Equilotl*

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Equilotl-linux
          path: |
            Equilotl-x11
            Equilotl-wayland
            Equilotl
            EquilotlCli-linux

  build-mac:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - arch: amd64
            runner: macos-15-intel
            artifact_name: Equilotl-macos
            gui_name: Equilotl-darwin-x64.zip
            cli_name: EquilotlCli-darwin-x64
          - arch: arm64
            runner: macos-latest
            artifact_name: Equilotl-macos-arm64
            gui_name: Equilotl-darwin-arm64.zip
            cli_name: EquilotlCli-darwin-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"

      - uses: actions/cache@v5
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ matrix.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-go-

      - name: Install dependencies
        run: brew install sdl2

      - name: Install Go dependencies
        run: go get -v

      - name: Build GUI
        run: |
          CGO_CFLAGS="-mmacosx-version-min=10.15" \
          CGO_LDFLAGS="-mmacosx-version-min=10.15" CGO_ENABLED=1 GOOS=darwin \
          GOARCH=${{ matrix.arch }} go build -v -tags "static gui" -ldflags "-s \
          -w -X 'equilotl/buildinfo.InstallerGitHash=$(git rev-parse --short \
          HEAD)' -X 'equilotl/buildinfo.InstallerTag=${{ env.RELEASE_TAG }}'" -o \
          Equilotl

      - name: Build CLI
        run: |
          CGO_CFLAGS="-mmacosx-version-min=10.15" \
          CGO_LDFLAGS="-mmacosx-version-min=10.15" CGO_ENABLED=1 GOOS=darwin \
          GOARCH=${{ matrix.arch }} go build -v -tags "cli" -ldflags "-s \
          -w -X 'equilotl/buildinfo.InstallerGitHash=$(git rev-parse --short \
          HEAD)' -X 'equilotl/buildinfo.InstallerTag=${{ env.RELEASE_TAG }}'" -o \
          ${{ matrix.cli_name }}

      - name: Update executable
        run: |
          chmod +x Equilotl*

      - name: Generate MacOS GUI bundle
        run: |
          mkdir -p Equilotl.app/Contents/MacOS
          mkdir -p Equilotl.app/Contents/Resources
          cp macos/Info.plist Equilotl.app/Contents/Info.plist
          mv Equilotl Equilotl.app/Contents/MacOS/Equilotl
          cp macos/icon.icns Equilotl.app/Contents/Resources/icon.icns

      - name: Ad-hoc sign the executables
        run: |
          codesign --force --deep --sign - Equilotl.app
          codesign --force --sign - ${{ matrix.cli_name }}

      - name: Create final zip
        run: zip -r ${{ matrix.gui_name }} Equilotl.app

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ${{ matrix.gui_name }}
            ${{ matrix.cli_name }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"

      - uses: actions/cache@v5
        with:
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit

      - name: Install Windows dependencies
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm git mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2

      - name: Install Go dependencies
        shell: msys2 {0}
        run: |
          go get -v
          go install github.com/tc-hib/go-winres@latest

      - name: Build GUI
        shell: msys2 {0}
        run: |
          go-winres make --product-version "git-tag"
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -v -tags "static gui" -ldflags "-s -w -H=windowsgui -extldflags=-static -X 'equilotl/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'equilotl/buildinfo.InstallerTag=${{ env.RELEASE_TAG }}'" -o Equilotl.exe

      - name: Build CLI
        shell: msys2 {0}
        run: |
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -v -tags "cli" -ldflags "-s -w -X 'equilotl/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'equilotl/buildinfo.InstallerTag=${{ env.RELEASE_TAG }}'" -o EquilotlCli.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Equilotl-windows
          path: |
            Equilotl.exe
            EquilotlCli.exe

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac, build-windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: "Download Linux Artifacts"
        uses: actions/download-artifact@v8
        with:
          name: Equilotl-linux
          path: linux

      - name: "Download MacOS Artifacts"
        uses: actions/download-artifact@v8
        with:
          name: Equilotl-macos
          path: macos

      - uses: actions/download-artifact@v8
        with:
          name: Equilotl-macos-arm64
          path: macos

      - name: "Download Windows Artifacts"
        uses: actions/download-artifact@v8
        with:
          name: Equilotl-windows
          path: windows

      - name: Create the release
        uses: softprops/action-gh-release@v3
        with:
          name: Release ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          make_latest: true
          draft: false
          body: |
            This is automated build ${{ env.RELEASE_TAG }} of Equilotl.
          files: |
            linux/Equilotl-x11
            linux/Equilotl-wayland
            linux/Equilotl
            linux/EquilotlCli-linux
            macos/Equilotl-darwin-x64.zip
            macos/Equilotl-darwin-arm64.zip
            macos/EquilotlCli-darwin-x64
            macos/EquilotlCli-darwin-arm64
            windows/Equilotl*.exe
